### PR TITLE
Add GitHub Actions CI Builds

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
Well for some reason I thought this did not have CI because I am use to looking for travis or github actions. Feel free to close if not interested.

### CODE REVIEW

**Comment by awinkler** [comment]
great, thanks, looks interesting! So what does this add additionally to:
1. the builds performed in this pull-request check as seen above.
2. The "build passing" badge on the readme pointing to the jenkins build (http://build.ros.org/view/Kdev/job/Kdev__ifopt__ubuntu_xenial_amd64/).
Is this just a different way to do CI?

**Comment by Levi-Armstrong** [comment]
I don't think it does anything additional, it is just uses githbub action. I am currently going through the repositories I maintain and one of them depends on this so I wanted to work on a windows CI build for this and for some reason did not notice you had CI setup. Would you be interested in a windows CI build? I recently work through this and do not think it would be to much trouble using github actions.

**Comment by awinkler** [comment]
Alright, thanks for the explanation. Let's keep the CI build done with the ROS build farm for now, I think that's sufficient. 

About the windows CI build, I wonder how many people are using windows and msbuild to build this and if that works out-of-the-box. I don't think you have to look into that for now. If some issues are filed in this direction back to you. 

Thanks anyway!

**Comment by Levi-Armstrong** [comment]
OK, I will try building on windows and if I have to add anything I will create a PR and add a windows CI build.

**Pull request closed without merging**
